language: java

before_script:
  - psql -U postgres -c "create user test with password 'test';"
  - psql -c 'create database test owner test;' -U postgres
 

script: ant -lib lib test

jdk:
 - openjdk6
